name: jannah
description: "المشروع: جنة هو مرافق رقمي مصمم لمساعدة المسلمين على تنظيم يومهم وفق الشعائر الإسلامية. يتميز التطبيق بفلسفة تصميمية فريدة تقوم على تيسير العبادة دون إشاعة التفاخر أو عدّ الأعمال الصالحة، من خلال ميزة التلاشي التدريجي للمهام المنجزة."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.8
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  geolocator: ^14.0.2
  get_it: ^9.2.1
  go_router: ^17.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  jhijri: ^1.0.0
  permission_handler: ^12.0.1
  provider: ^6.1.5+1
  qcf_quran_plus: ^0.0.7
  scrollable_positioned_list: ^0.3.8
  shared_preferences: ^2.5.5
  widgets_box: ^0.1.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/data/
    - assets/images/
